service: react-apollo-pokedex
plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
